``` {r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

## Soil chemistry and nutrient availability

The focus in terrestrial ecology is typically on carbon (C) and nitrogen (N), and to a lesser extent on phosphorus (P). But other nutrients such as potassium (K), magnesium (Mg), calcium (Ca), and zinc (Zn) can limit plant growth and influence ecosystem behaviour when in short supply (see e.g. Sardans & Peñuelas, 2015). However, the availability of individual nutrients can be difficult to assess, as, for example, no perfect method exists to determine availability of N or P to plants (Binkley & Hart, 1989; Holford, 1997; Neyroud & Lischer, 2003). Commonly used proxies are N mineralisation (protocol 2.2.5 [Nutrient mineralisation]), soil NO3 and NH4 concentrations (Keeney & Nelson, 1982), soil C:N ratio (protocol 2.2.4 [Soil carbon and nutrient stocks]), Olsen P and Bray P (Bray & Kurtz, 1945; Olsen, 1954), and/or ion exchange resin membranes like Plant Root Simulator (PRS) probes (1.4.2 Soil nutrient), but these all have their drawbacks (Binkley & Hart, 1989; Holford, 1997; Neyroud & Lischer, 2003). Although no perfect method exists to determine nutrient availability, some soil properties are very indicative of the nutrient status of a soil (Vicca et al., 2018). These include bedrock, texture (1.3.5 Soil texture), pH (1.4.1 Soil pH), bulk density (1.3.4 Bulk density), cation exchange capacity, and soil organic matter (SOM). These key soil physical properties are relatively easy to measure and in combination are very indicative of the nutrient status (see e.g. Van Sundert et al., 2018; Vicca et al., 2018). These data on soil properties and nutrients allow disentangling the role of nutrient availability as well as classifying a study site as nutrient-poor, nutrient-rich, or moderately fertile (_sensu_ Vicca et al., 2012; Terrer et al., 2016). Plant N and P uptake can be calculated from plant N and P concentrations and plant growth: 

N uptake = plant growth x [N]

N and P concentrations are important to determine the nutrient status of a study and thus important information for modelling and meta-analysis (see Table 2 in the main paper). Other variables that can be of relevance in some cases are described in Supporting Information [Stress physiology] and [Carbon and nutrient cycling]. Below, we present a brief description of complementary measurements that are relatively easy to conduct routinely at any site or study and can provide a robust characterisation of nutrient availability across sites. This list largely corresponds to the measurements recently suggested in Vicca et al. (2018), which we refer to for further reading on the interpretation and relevance of the different measurements.

### Soil pH (unitless)

pH is a measure of acidity in the soil and affects many chemical processes, such as plant nutrient availability. Most soil methods are conducted on air-dry soil: however, given that understanding the chemical environment that plants experience is important in ecosystem studies, we propose the use of field-moist soil in preference to dried soil for pH measurements. Soil pH is then carried out on a suspension of fresh field-moist soil in deionised water (DIW), or 0.01 M KCl or CaCl2. Often both DIW and a saline suspensions are measured because both values provide different information. Soils in their natural condition can vary widely in the salt content, also within the same soil the concentration of salts vary with the variation in soil water content, these variations in salinity have an effect in the measurements of pH.

The impact of these variations on pH is minimised when measured in 0.01 M of a saline solution and allows valid comparisons of soil pH between seasons and years.

**_What and how to measure_**

We focus on measurements in water. The soil:water ratio depends on the amount of organic matter in the soil with a ratio of soil to water of 1:2.5 to 1:5 by weight for mineral soil. The method described here is based upon that employed by the Soil Survey of England and Wales (Avery & Bascomb, 1974) and by the Countryside Survey (Emmett et al., 2010), but measuring soil pH in deionised water using a 1:1 mixture is reported in the NRCS (2014) handbook. Organic soils, however, require a much higher ratio of soil to water of 1:10 or 1:20 by weight Calibrate the pH meter in buffer solutions. Check pH 4 & 7 buffer calibrations regularly within a sample batch, for example every 10 samples. If either buffer calibration is more than 0.02 of a pH unit from the correct value, repeat calibration. Weigh 10 g of fresh field-moist soil into a 50 ml plastic pH beaker. Add 25 ml of deionised water and stir the suspension thoroughly. Allow it to stand for 30 minutes, stirring occasionally. Measure soil pH electrometrically using the calibrated pH meter. Include a suitable number of duplicate samples, i.e. carry out the pH measurement twice on approximately one-tenth of the samples. Thoroughly rinse the pH probe between samples with a stream of water from a deionised water wash bottle. Ensure the glass bulb of the pH probe is cleared of soil and be particularly thorough after probes have been immersed in pH buffers. If duplicated samples are not in agreement, repeat the measurements on a small set of samples; from this set of information, determine whether outliers skewed the measurements (remove the outliers if there is good reason, e.g. instrument failure), or whether soil pH was highly variable (report average and standard deviation). New probes for field measurements of pH are available for instant and fast pH measurements, which enables high-resolution measurement of pH in space and time (e.g. Nielsen et al., 2017).

### Soil nutrients

**Integrated assessment of soil cation and nutrient availability for plants**

Resin membranes like Plant Root Simulator (PRS) probes (Western AG, Saskatchewan, Canada) absorb anions or cations (depending on the type of probe) that are in the soil solution. They thus provide an indication of the nutrient availability as experienced by the biota during the time of burial and are particularly useful for assessing relative differences among treatments and studies. The probes are inserted into the soil for a short period (e.g. 7 days) and are subsequently analysed in the lab for the nutrients of interest (e.g. NO~3~, NH^4^, P, K, Ca, Mg, Mn, Fe, Zn). The results indicate the flux of each of these nutrients over the time of burial. Caution is needed to avoid saturation of the probes (i.e. burial time should not be too long) and the absorption of ions is sensitive to soil moisture, which may complicate interpretation in studies where soil moisture differs between the treatments. More information is available from the website of the commercially available PRS probes ([https://www.westernag.ca/innov](https://www.westernag.ca/innov)). Instead of buying the commercial product, it is also possible to produce the probes for low cost (see protocol 2.2.5. [Nutrient mineralisation]).

**Cation exchange capacity, exchangeable base cations, and soil electrical conductivity**
One of the most important properties of soil colloids (clay and organic matter particles < 0.001 mm diameter) is their ability to adsorb, hold, and release ions. Colloids are generally negatively charged and thus attract primarily positively charged ions, i.e. cations. The more negative charges, the higher the capacity of the soil to bind cations, and thus the higher its **cation exchange capacity** (CEC, typically expressed as the amount of positive charges that can be exchanged per mass of soil). For soil fertility, the **total exchangeable base cations** (Mg~2~^+^, Ca~2~^+^, and K^+^ in particular) are especially relevant. These are the base cations bound to the negatively charged colloids. They can be taken up relatively easily by plant roots through exchange for H+. The fraction of CEC that is occupied by exchangeable base cations is termed base saturation. This fraction can be small, especially in acidic and leached soils where many of the negative charges are occupied by (acidic) cations, such as H+, Al~3~^+^, or Fe~3~^+^.

**_What and how to measure_**

Cation exchange capacity and total exchangeable base cations can be determined using the most common method of Brown (1943), for which 1 M buffer ammonium acetate solution (NH~4~Ac) at pH 7 serves as the extractant. Soil samples are collected and sieved (< 2mm) and air dried.

**Soil electrical conductivity (EC; mS m^–1^)**
This is the ability of soil to conduct an electrical current and is commonly expressed in units of milliSiemens per metre (mS m^–1^). EC estimates the concentration of ions in the soil, namely the anions Cl^-^, SO~4~^2-^, and HCO~3~^-^ and the cations Na^+^, Ca^2+^, K^+^, and Mg^2+^ (Friedman, 2005; He et al., 2012). Although the relationship between conductivity and salt concentration varies somewhat depending on ionic composition, EC provides a simple and reasonably accurate estimate of solute concentration (Carter & Gregorich, 2006). In addition, as soil EC is affected by several soil properties, its measurement can also be used as a proxy for estimating directly or indirectly the variations in these properties, including soil texture, bulk density, soil water content, water-holding capacity, cation exchange capacity, organic matter, and subsoil characteristics (Corwin & Lesch, 2005a; Grisso et al., 2005). For this reason, over the years, EC has been largely used in agriculture to estimate soil salinity, nutrient availability and loss, soil texture, and available water capacity, being considered a reliable and cost-effective measurement (NRCS, 2014). As an example, high EC values often reflect poor plant growth conditions and the potential for salinity problems (Karlen et al., 2008). As this variable has been shown to be closely related with distinct soil properties, its measurement assumes special importance under the context of climate change where some properties are expected to alter with consequences for soil quality and its functioning. 

**_What and how to measure_**

The first measurements of soil EC were made on soil samples, but it was found to be more consistent to measure EC in soil extracts. Hence, the standard laboratory method for determining the EC of a soil is by using an aqueous paste extract of soil and to measure the electrical conductivity of the solution using a conductivity meter (Richard, 1954; Carter & Gregorich, 2006). The determination is carried out to obtain an indication of the content of water-soluble electrolytes in a soil. Because the saturated paste extract method requires time and skill, a fixed soil:water ratio (e.g., 1:1 to 1:5) has been generalised when measuring soil EC and solute concentrations (ISO 11265, 1994). Knowing that EC in soil is dependent on several properties and therefore is highly variable, several samples should be taken from multiple locations. Besides the methods based on an aqueous paste extract of soil, the apparent EC (ECa, bulk soil electrical conductivity) has become one of the most frequently used measurements to characterise the spatial distribution of soil salinity at field scales. Nowadays, ECa is considered an invaluable tool for the establishment of spatial variation and for identifying the soil properties influencing crop production in precision agriculture (Corwin & Lesch, 2005a, 2005b). ECa has also been used to identify homogeneous areas within a field to implement experiments. Field methods used to measure ECa include the Wenner array or four-electrode, time domain reflectometry (TDR) and electromagnetic (EM) induction (Carter & Gregorich, 2006). The EM method, by using a non-contact sensor, is the most commonly used because measurements can be taken quickly over large areas, the large volume of soil measured reduces local scale variability, and measurements are possible on relatively dry or stony soils because contact is not required between soil and sensor (Hendrickx et al., 1990).

**Carbon and nutrient stocks** 

The soil carbon and nutrient stock is the amount of C, N, P, K, and other nutrients stored in the soil. These stocks are coupled with net primary production and decomposition of above- and belowground material and highly related to climate. For further details and how to measure see protocol 2.2.4 [Soil carbon and nutrient stocks]. 

**Soil organic matter (SOM, %)** 

It is important to determine the soil organic matter (SOM), as changes in environmental factors such as temperature or water inputs may alter the SOM content (directly and indirectly by influencing organic matter inputs), and variation among studies may also be explained by differences in SOM. Soil organic matter can be determined using the Walkley Black method or the loss-on-ignition (LOI) procedure described in Nelson & Sommers (2009). LOI is generally preferred over the Walkley Black method because is less time consuming. One of the aspects to consider when measuring LOI is the choice of combustion temperature in the furnace and the duration of time used for combustion.

**_What and how to measure_**

We propose the method of Ball (1964) which is determined by subtracting the weight of a soil after 16 h drying at 105 °C from a soil after placing in a furnace overnight at 375 °C. The amount of soil used to determine SOM is adjustable but should not be lower than 10 g fresh soil to ensure a representative sample. For more details also see Countryside Survey (Emmett et al., 2010).

**Soil inorganic carbon (mass fraction: g C g soil ^-1^)**

Some soils contain significant amounts of carbonates, especially soils in dry climates. Changes to warming or the precipitation regime may alter the carbonate content. Reporting carbonates is not routine, but may be important if a total carbon balance is required. We refer the reader to the methods described in Nelson & Sommers (2009).

### Soil trace metals

Trace metals are a group of metals and metalloids (e.g. arsenic (As) and selenium (Se); hereinafter called “metal”) found in low concentrations (< 100 mg kg^–1^), in mass fractions of ppm or less, in some specified source, for example, soil, water, plant, or tissue (Duffus, 2002; Hooda, 2010). The most common trace metals are beryllium (Be), aluminium (Al), vanadium (V), chromium (Cr), manganese (Mn), iron (Fe), cobalt (Co), nickel (Ni), copper (Cu), zinc (Zn), As, Se, molybdenium (Mo), silver (Ag), cadmium (Cd), antimony (Sb), mercury (Hg), thallium (TI), and lead (Pb). Trace metals are important elements in the biogeochemistry of terrestrial ecosystems (Driscoll et al., 1994). The concentration of trace metals in soil directly relates to the growth and development of vegetation and reflects the supply of mineral nutrition to plants by soil (Zhanbin et al., 2013). Depending on the dose, trace metals can become potentially toxic for life (Kabata-Pendias & Mukherjee, 2007; Kabata-Pendias, 2010). Although trace metals are naturally present in soils (Kabata-Pendias & Mukherjee, 2007; Kabata-Pendias, 2010), their concentrations in soils are significantly influenced by anthropogenic activities, which greatly alter the biogeochemical cycles of trace metals and their bioavailability (Driscoll et al., 1994). The observed changes in soil properties could affect soil functioning through their impacts on the composition and activity of microbial communities, which can provoke toxic responses in soil microorganisms, including reducing microbial biomass and decreasing carbon mineralisation and disturbing enzymatic activities. Furthermore, metal stress has been found to change the structure and diversity of microbial communities (Certini, 2005; Hart et al., 2005; Hartmann et al., 2005; Frey et al., 2006). This eventually affects the biogeochemical system’s functions driven by these organisms, since soil microorganisms are important agents in nutrient cycling and energy flow. Assessing the levels of trace metals in soils is crucial to determining the environmental impacts of climate change on soil quality, structure, and functioning (Curran-Cournane et al., 2015).

**_What and how to measure?_**

**Total concentration of trace metals in soils:** sample digestion is often a necessary step before determining total element mass concentration in soils. Various digestion methods are used to determine the mass concentration of trace metals in soils, including different combinations of concentrated acids (Gaudino et al., 2007). The dissolution of soil samples can be obtained by rigorous digestion using the standardised aqua regia extraction protocol which consists of treating a soil sample in a heated 3:1 mixture of hydrochloric (HCl) and nitric (HNO3) acids (ISO 11466, 1995; USEPA 3050B, 1996). This is a partial digestion of the soil solid phase consisting of a very strong acid digestion that dissolves almost all elements that become “environmentally available” (McLean & Bledsoe, 1992; USEPA 3050B, 1996; USEPA 3051A, 2007). Although the aqua regia digestion method is internationally accepted to measure concentrations in soil, fractions of elements extracted by this method are not available for biological uptake (Gaudino et al., 2007). If a total trace metals concentration is required, the soil samples are treated with a mixture of HNO~3~ + HCl+ HF (hydrofluoric acid) using microwave heating with a suitable laboratory microwave system (USEPA 3052, 1996; EN 13656, 2002). After the extraction procedures (ISO 11466, 1995; USEPA 3050B, 1996; USEPA 3052, 1996; EN 13656, 2002; USEPA 3051A, 2007), the extract is filtered through 0.45μm nitrocellulose membrane filters, diluted, and analysed by atomic absorption spectrometry (flame: FAAS or graphite furnace: GFAS) or inductively coupled plasma spectrometry (optical emission: ICP-OES or mass: ICP-MS).

Another commonly used procedure to measure the “total” concentration of trace metals is the digestion with hot HNO~3~ and hydrogen peroxide (H~2~O~2~) procedure also outlined in USEPA 3050B (1996). This method adds H~2~O~2~ in order to enhance the destruction of the organic matter in soil.

**Sequential extractions of trace metals in soils:** chemical extraction is employed to operationally define trace metal fractions, which can be related to chemical species, as well as to potential mobile, bioavailable, or ecotoxicological phases of a sample. Fractionation is usually performed by a sequence of selective chemical extraction techniques, including the successive removal, or dissolution, of these phases and their associated metals (Hlavay et al., 2004). The extraction procedures consist of reacting a soil sample with increasing strengths of chemical solutions. Numerous extraction procedures have been developed for trace metals (Sposito et al., 1982; McLean & Bledsoe, 1992; Singh et al., 1998; Wenzel et al., 2001; Imperato et al., 2003; Hlavay et al., 2004; Hooda, 2010). Supernatants from each fraction will be analysed by FAAS, GFAA, ICP-OES or ICP-MS. For the Sequential extraction there are numerous methods using different extractants at different concentrations. For example, extraction with specific extracting agents, especially containing chelating agents, allows examination of the distribution of soluble exchangeable forms. Ethylenediaminetetraacetic acid (EDTA), used as extracting agent for many trace elements, has been widely applied in soil science and environmental chemistry (Kocialkowski et al., 1999; Michaud et al., 2007; Komárek et al., 2008).

### References

Avery, B. W., & Bascomb, C. L. (1974). _Soil Survey Technical Monograph No. 6. Soil survey laboratory methods._ Dorking, UK: Adlard & Son Ltd.

Ball, D. F. (1964). Loss-on-ignition as an estimate of organic matter and organic carbon in non-calcareous soils. _European Journal of Soil Science_, 15(1), 84–92.

Binkley, D., & Hart, S. C. (1989). The components of nitrogen availability assessments in forest soils. In B. A. Stewart (Ed.), _Advances in Soil Science_ (pp. 57–112). New York, NY: Springer.

Bray, R. H., & Kurtz, L. T. (1945). Determination of total, organic, and available forms of phosphorus in soils. _Soil Science_, 59(1), 39–46.

Brown, I. C. (1943). A rapid method of determining exchangeable hydrogen and total exchangeable bases of soils. _Soil Science_, 56(5), 353.

Carter, M. R., & Gregorich, E. G. (2006). _Soil Sampling and Methods of Analysis_ (Vol. 44). Boca Raton: CRC Press.

Certini, G. (2005). Effects of fire on properties of forest soils: a review. _Oecologia_, 143(1), 1–10.

Corwin, D. L., & Lesch, S. M. (2005a). Apparent soil electrical conductivity measurements in agriculture. _Computers and Electronics in Agriculture_, 46(1), 11–43.

Corwin, D. L., & Lesch, S. M. (2005b). Characterizing soil spatial variability with apparent soil electrical conductivity: I. Survey protocols. _Computers and Electronics in Agriculture_, 46(1), 103–133.

Curran-Cournane, F., Lear, G., Schwendenmann, L., & Khin, J. (2015). Heavy metal soil pollution is influenced by the location of green spaces within urban settings. _Soil Research_, 53(3), 306–315.

Driscoll, C. T., Otton, J. K., & Iverfeldt, Å. (1994). Trace metals speciation and cycling. In B. Moldan & J. Cerny (Eds.), _Biogeochemistry of Small Catchments: a tool for environmental research_ (pp. 299–322). John Wiley & Sons.

Duffus, J. H. (2002). _Heavy Metals – A Meaningless Term?_ (vol. 74, pp. 793–807). IUPAC Technical Report.

Emmett, B. A., Reynolds, B., Chamberlain, P. M., Rowe, E., Spurgeon, D., Brittain, S. A., … Woods, C. (2010). _Countryside Survey: soils report from 2007_ (No. 9/07). Centre for Ecology & Hydrology (Natural Environment Research Council).

EN 13656. (2002). EN 13656 – Characterization of waste. Microwave assisted digestion with hydrofluoric (HF), nitric (HNO3), and hydrochloric (HCl) acid mixture for subsequent determination of elements. European Committee for Standardization.

Frey, B., Stemmer, M., Widmer, F., Luster, J., & Sperisen, C. (2006). Microbial activity and community structure of a soil after heavy metal contamination in a model forest ecosystem. _Soil Biology and Biochemistry_, 38(7), 1745–1756.

Friedman, S. P. (2005). Soil properties influencing apparent electrical conductivity: a review. _Computers and Electronics in Agriculture_, 46(1), 45–70.

Gaudino, S., Galas, C., Belli, M., Barbizzi, S., de Zorzi, P., Jaćimović, R., … Sansone, U. (2007). The role of different soil sample digestion methods on trace elements analysis: a comparison of ICP-MS and INAA measurement results. _Accreditation and Quality Assurance_, 12(2), 84–93.

Grisso, R. D., Alley, M. M., Holshouser, D. L., & Thomason, W. E. (2005). Precision farming tools: soil electrical conductivity, 442(508), 1–6.

Hart, S. C., DeLuca, T. H., Newman, G. S., MacKenzie, M. D., & Boyle, S. I. (2005). Post-fire vegetative dynamics as drivers of microbial community structure and function in forest soils. _Forest Ecology and Management_, 220(1), 166–184.

Hartmann, M., Frey, B., Kölliker, R., & Widmer, F. (2005). Semi-automated genetic analyses of soil microbial communities: comparison of T-RFLP and RISA based on descriptive and discriminative statistical approaches. _Journal of Microbiological Methods_, 61(3), 349–360.

He, Y., DeSutter, T., Prunty, L., Hopkins, D., Jia, X., & Wysocki, D. A. (2012). Evaluation of 1:5 soil to water extract electrical conductivity methods. _Geoderma_, 185-186, 12–17.

Hendrickx, J. M. H., Baerends, B., Raza, Z. I., Sadig, M., & Akram Chaudhry, M. (1990). Soil salinity assessment by electromagnetic induction of irrigated land. _Soil Science Society of America Journal_, 56, 1933–1941.

Hlavay, J., Prohaska, T., Weisz, M., Wenzel, W. W., & Stingeder, G. J. (2004). Determination of trace elements bound to soil and sediment fractions (IUPAC Technical Report). _Journal of Macromolecular Science, Part A: Pure and Applied Chemistry_, 76(2), 415–442.

Holford, I. C. R. (1997). Soil phosphorus: its measurement, and its uptake by plants. _Soil Research_, 35(2), 227–240.

Hooda, P. S. (2010). _Trace Elements in Soils_. John Wiley & Sons.

Imperato, M., Adamo, P., Naimo, D., Arienzo, M., Stanzione, D., & Violante, P. (2003). Spatial distribution of heavy metals in urban soils of Naples city (Italy). _Environmental Pollution_, 124(2), 247–256.

ISO 11265. (1994). ISO 11265. _Soil quality – Determination of the specific electrical conductivity_. Geneva: International Organization for Standardization.

ISO 11466. (1995). ISO 11466. _Soil quality – Extraction of trace elements soluble in aqua regia_. Geneva: International Organization for Standardization.

Kabata-Pendias, A. (2010). _Trace Elements in Soils and Plants (Fourth Edition)_. Boca Raton: CRC Press.

Kabata-Pendias, A., & Mukherjee, A. B. (2007). _Trace Elements from Soil to Human_. Springer Science & Business Media.

Karlen, D. L., Andrews, S. S., Wienhold, B. J., & Zobeck, T. M. (2008). Soil quality assessment: Past, present and future. _Electronic Journal of Integrative Biosciences_, 3, 3–14.

Keeney, D. R., & Nelson, D. W. (1982). Nitrogen — Inorganic forms. In A. L. Page, R. H. Miller, & D. R. Keeney (Eds.), _Methods of Soil Analysis, Part 2—Chemical and Microbial Properties_ (pp. 643–698). Madison, WI: Soil Science Society of America Inc.

Kocialkowski, W. Z., Diatta, J. B., & Grzebisz, W. (1999). Evaluation of chelating agents as heavy metals extractants in agricultural soils under threat of contamination. _Polish Journal of Environmental Studies_, 8(3), 149–154.

Komárek, M., Száková, J., Rohošková, M., Javorská, H., Chrastný, V., & Balík, J. (2008). Copper contamination of vineyard soils from small wine producers: A case study from the Czech Republic. _Geoderma_, 147(1), 16–22.

McLean, J. E., & Bledsoe, B. E. (1992). _Behaviour of Metals in Soils (EPA Ground Water Issue)_ (pp. 1–25). Washington, USA: Environmental Protection Agency.

Michaud, A. M., Bravin, M. N., Galleguillos, M., & Hinsinger, P. (2007). Copper uptake and phytotoxicity as assessed in situ for durum wheat (Triticum turgidum durum L.) cultivated in Cu-contaminated, former vineyard soils. _Plant and Soil_, 298(1-2), 99–111.

Nelson, D. W., & Sommers, L. E. (2009). Total carbon, organic carbon, and organic matter. _In Methods of Soil Analysis part 3—Chemical Methods_ (pp. 961–1010). Soil Science Society of America, American Society of Agronomy.

Neyroud, J.-A., & Lischer, P. (2003). Do different methods used to estimate soil phosphorus availability across Europe give comparable results? _Journal of Plant Nutrition and Soil Science_, 166(4), 422–431.

Nielsen, K. E., Irizar, A., Nielsen, L. P., Kristiansen, S. M., Damgaard, C., Holmstrup, M., … Strandberg, M. (2017). In situ measurements reveal extremely low pH in soil. _Soil Biology and Biochemistry_, 115, 63–65.

NRCS Natural Resources Conservation Service. (2014). _Soil Electrical Conductivity: Soil Health – Guides for educators_. United States Department of Agriculture.

Olsen, S. R. (1954). _Estimation of available phosphorus in soils by extraction with sodium bicarbonate_. United States Department of Agriculture.

Richard, L. A. (1954). _Diagnosis and improvement of saline and alkalie soils (Agriculture Handbook No. 60)_. United States Department of Agriculture.

Sardans, J., & Peñuelas, J. (2015). Potassium: a neglected nutrient in global change. _Global Ecology and Biogeography_, 24(3), 261–275.

Singh, S. P., Tack, F. M., & Verloo, M. G. (1998). Heavy metal fractionation and extractability in dredged sediment derived surface soils. _Water, Air, and Soil Pollution_, 102(3-4), 313–328.

Sposito, G., Lund, L. J., & Chang, A. C. (1982). Trace metal chemistry in arid-zone field soils amended with sewage sludge: I. Fractionation of Ni, Cu, Zn, Cd, and Pb in solid phases. _Soil Science Society of America Journal_, 46(2), 260–264.

Sundert, K. V., Horemans, J. A., Stendahl, J., & Vicca, S. (2018). The influence of soil properties and nutrients on conifer forest growth in Sweden, and the first steps in developing a nutrient availability metric. _Biogeosciences_ 15(11), 3475-3496.

Terrer, C., Vicca, S., Hungate, B. A., Phillips, R. P., & Prentice, I. C. (2016). Mycorrhizal association as a primary control of the CO2 fertilization effect. _Science_, 353(6294), 72–74.

USEPA 3050B. (1996). Method 3050B: _Acid digestion of sediments, sludges and soils. Methods for evaluating solid waste_. Washington: United States Environmental Protection Agency.

USEPA 3051A. (2007). Method 3051: _Microwave assisted acid digestion of sediments, sludges, soils and oils. Methods for evaluating solid waste_. Washington: United States Environmental Protection Agency.

USEPA 3052. (1996). Method 3052: _Microwave assisted acid digestion of siliceous and organically based matrices. Methods for evaluating solid waste_. Washington: United States Environmental Protection Agency.

Vicca, S., Luyssaert, S., Peñuelas, J., Campioli, M., Chapin, F. S.,, Ciais, P., … Janssens, I. A. (2012). Fertile forests produce biomass more efficiently. _Ecology Letters_, 15(6), 520–526.

Vicca, S., Stocker, B. D., Reed, S., Wieder, W. R., Bahn, M., Fay, P. A., … Ciais, P. (2018). Using research networks to create the comprehensive datasets needed to assess nutrient availability as a key determinant of terrestrial carbon cycling. _Environmental Research Letters_, 13(12), 125006.

Wenzel, W. W., Kirchbaumer, N., Prohaska, T., Stingeder, G., Lombi, E., & Adriano, D. C. (2001). Arsenic fractionation in soils using an improved sequential extraction procedure. _Analytica Chimica Acta_, 436(2), 309–323.

Zhanbin, L., Qinling, Z., & Peng, L. (2013). Distribution characteristics of available trace elements in soil from a reclaimed land in a mining area of north Shaanxi, China. _International Soil and Water Conservation Research_, 1(1), 65–75.
