``` {r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Site Characteristics and Data Management

**Editor:** Halbritter AH

**Authors:** Halbritter AH^1^, Robinson DA^2^, Reinsch S^2^, Lebron I^2^, Abrantes N^3^, Campos I^3^, Zurba K^4^, Vicca S^5^, Cosby J^2^, van der Ploeg M^6^, Telford RJ^1^ and Vandvik V^1^

**Reviewers:** Chojnicki BH^7^, Lee H^8^, Stuart-Haëntjens E^9^, De Boeck HJ^5^

Systematic reporting of basic site information of the studied system is necessary to ensure that studies are repeatable and to enable data re-use across studies, syntheses, modelling, and upscaling (Haddaway & Verhoeven, 2015; Gerstner et al., 2017). In climate change research, there are experiments _sensu stricto_ and natural experiments in space (i.e. gradient studies) and time (i.e. observational studies). This chapter on reporting and documentation is applicable to all these types of studies (if not otherwise specified). In addition, many of the principles discussed in this chapter are not exclusively relevant for climate-change studies, but also apply to global-change studies in general.

Surprisingly, the necessary basic site information of studies, is often incomplete or missing in scientific publications (Hillebrand & Gurevitch, 2013). In this chapter we therefore describe which key site, study system, and study design variables and information should be collected, and how this information is best reported.

We first discuss how to design and set up an experiment or observational study that may serve multiple uses beyond the needs of the particular project. Then we describe basic geographical location and basic site description (e.g. coordinates, elevation, land-use history, vegetation), physical (e.g. soil horizon, pH), chemical (e.g. nutrient availability), and meteorological variables, and finally how to report your data. Although some of this information may not directly relate to the particular research question or hypotheses, reporting all relevant site information is essential as it puts the study in a larger context and is the key to making data and results useful beyond the particular research for which they were designed.

#### References {-}

Gerstner, K., Moreno-Mateos, D., Gurevitch, J., Beckmann, M., Kambach, S., Jones, H. P., & Seppelt, R. (2017). Will your paper be used in a meta-analysis? Make the reach of your research broader and longer lasting. _Methods in Ecology and Evolution_, _8_(6), 777-784.

Haddaway, N. R., & Verhoeven, J. T. A. (2015). Poor methodological detail precludes experimental repeatability and hampers synthesis in ecology. _Ecology and Evolution_, _5_(19), 4451-4454.

Hillebrand, H., & Gurevitch, J. (2013). Reporting standards in experimental studies. _Ecology Letters_, _16_(12), 1419-1420.

#### Affiliations {-}

^1^ Department of Biological Sciences and Bjerknes Centre for Climate Research, University of Bergen, Bergen, Norway

^2^ Centre for Ecology & Hydrology, Environment Centre Wales, Bangor, UK

^3^ Centre for Environmental and Marine Studies (CESAM), Department of Environment and Planning, University of Aveiro,3810-193 Aveiro, Portugal

^4^ Interdisciplinary Environmental Research Centre, Technische Universität Bergakademie Freiberg, Germany

^5^ Centre of Excellence PLECO (Plants and Ecosystems), Biology Department, University of Antwerp, Wilrijk, Belgium

^6^ Soil Physics and Land Management, Wageningen University, the Netherlands

^7^ Poznań University of Life Sciences; Meteorology Department, Poznań, Poland

^8^ NORCE Norwegian Research Centre and Bjerknes Centre for Climate Research, Bergen, Norway

^9^ Department of Biology, Virginia Commonwealth University, Richmond, VA USA
